# Penerapan Aljabar Linear dalam Python

Referensi latihan dan belajar di web w3schools (Numpy tutorial)

In [13]:
import numpy as np #Numpy = numerical python

P = np.array([[1, 7], [2, 3], [5, 0]])
Q = np.array([[2, 6, 3, 1], [1, 2, 3, 4]])
print(P)
print(Q)
print(np.dot(P, Q))
np.dot(P, Q)


[[1 7]
 [2 3]
 [5 0]]
[[2 6 3 1]
 [1 2 3 4]]
[[ 9 20 24 29]
 [ 7 18 15 14]
 [10 30 15  5]]


array([[ 9, 20, 24, 29],
       [ 7, 18, 15, 14],
       [10, 30, 15,  5]])

In [6]:
v = np.array([[0, 3, 2]])
w = np.array([[4, 1, 1]])
u = np.array([[0, -2, 0]])
x = 3*v-2*w+4*u
print(x)

[[-8 -1  4]]


In [11]:
a = np.array([[2, -1], 
              [3, 4 ],
              ])
b = np.array([[3, -9, 2],
              [5, 7 , -6]
              ])

#Saat di print tanda koma hilang karena dianggap sebagai matrix
print(a)
print(b)
print(np.dot(a, b)) 



[[ 2 -1]
 [ 3  4]]
[[ 3 -9  2]
 [ 5  7 -6]]
[[  1 -25  10]
 [ 29   1 -18]]


In [21]:
#Slicing dalam matrix 

b = np.array([[3, -9, 2],
              [5, 7, -6],
              [3, 4, 5],
              [2, 3, 4],
              [2, 2, 3]
              ])

print(b[1:][1::2])

[[3 4 5]
 [2 2 3]]
